name: bitcoin_sniper_env
channels:
  - defaults
dependencies:
  # Ganti dadi 3.11
  - python=3.11
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - mlflow==2.17.2
    - dagshub
    - virtualenv