name: bitcoin_sniper_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - mlflow<3
    - dagshub
    - virtualenv